// Code generated by hertz generator.

package auth

import (
	"context"

	"empyrean_lens/service"
	"github.com/cloudwego/hertz/pkg/app"
)

// Login .
// @router /auth/login [GET]
func Login(ctx context.Context, c *app.RequestContext) {
	service.NewAuthService().Login(ctx, c)
}

// Callback .
// @router /auth/callback [GET]
func Callback(ctx context.Context, c *app.RequestContext) {
	service.AuthMiddleware().LoginHandler(ctx, c)
}

// Me .
// @router /api/auth/me [GET]
func Me(ctx context.Context, c *app.RequestContext) {
	service.NewAuthService().Me(ctx, c)
}

// Logout .
// @router /api/auth/logout [POST]
func Logout(ctx context.Context, c *app.RequestContext) {
	service.AuthMiddleware().LogoutHandler(ctx, c)
}
