// Code generated by hertz generator.

package auth

import (
	"context"

	auth_model "empyrean_lens/biz/model/empyrean_lens/auth"
	"empyrean_lens/service"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Configuration OIDC Discovery 文档，接入方通过此端点自动发现 SSO 能力（RFC 8414）。
// @router /.well-known/openid-configuration [GET]
func Configuration(ctx context.Context, c *app.RequestContext) {
	service.NewOidcService().Configuration(ctx, c)
}

// UserInfo 标准 OIDC UserInfo 端点（OIDC Core §5.3），返回标准字段名（sub/picture）。
// @router /userinfo [GET]
func UserInfo(ctx context.Context, c *app.RequestContext) {
	service.NewOidcService().UserInfo(ctx, c)
}

// Introspect 标准 Token Introspection 端点（RFC 7662），token 在 POST body form 里。
// @router /introspect [POST]
func Introspect(ctx context.Context, c *app.RequestContext) {
	var req auth_model.IntrospectReq
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	service.NewOidcService().Introspect(ctx, c, &req)
}

// Token 标准 OAuth2 Token 端点（RFC 6749 §4.1.3）。
// 接入方用 authorization_code 换取 access_token，须提供 client_id + client_secret。
// @router /token [POST]
func Token(ctx context.Context, c *app.RequestContext) {
	var req auth_model.TokenReq
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	service.NewOidcService().Token(ctx, c, &req)
}
