// Code generated by hertz generator.

package main

import (
	"empyrean_lens/conf"
	"empyrean_lens/dal"

	"codeup.aliyun.com/deeplang/lingowhale/lingowhale_backend/go_lib/logger"
	"codeup.aliyun.com/deeplang/lingowhale/lingowhale_backend/go_lib/metrics"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	conf.InitConfig()
	logger.Init(conf.GetConfig().Logger)
	// metrics init
	metrics.Init(conf.GetConfig().Metrics)
	dal.Init()

	h := server.Default(server.WithHostPorts(conf.GetConfig().Server.Port))

	register(h)
	h.Spin()
}
