// Code generated by hertz generator.

package main

import (
	"context"
	"empyrean_lens/conf"
	"empyrean_lens/dal"
	"empyrean_lens/tools"
	"empyrean_lens/utils"
	"path/filepath"
	"strings"

	"codeup.aliyun.com/deeplang/lingowhale/lingowhale_backend/go_lib/logger"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/middlewares/server/recovery"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

func main() {

	conf.InitConfig()
	logger.Init(conf.GetConfig().Logger)
	dal.Init()

	runner := tools.ProbeRunner{}
	runner.Run(context.Background())

	h := server.Default(server.WithHostPorts(conf.GetConfig().Server.Port))

	// Recovery 兜底策略
	h.Use(recovery.Recovery(recovery.WithRecoveryHandler(RecoveryHandler)))

	register(h)
	staticFs(h)
	h.Spin()
}

func staticFs(h *server.Hertz) {
	root := utils.GetProjectPath()
	h.StaticFS("/public", &app.FS{
		Root: filepath.Join(root, "./static/"),
		PathRewrite: func(ctx *app.RequestContext) []byte {
			path := string(ctx.Path())
			after, found := strings.CutPrefix(path, "/public")
			if found {
				return []byte(after)
			}
			return []byte("")
		},
	})
	h.StaticFS("/api/static", &app.FS{
		Root: filepath.Join(root, "./static"),
		PathRewrite: func(ctx *app.RequestContext) []byte {
			path := string(ctx.Path())
			after, found := strings.CutPrefix(path, "/api/static")
			if found {
				return []byte(after)
			}
			return []byte("")
		},
	})
}

func RecoveryHandler(c context.Context, ctx *app.RequestContext, err interface{}, stack []byte) {
	defer func() {
		if r := recover(); r != nil {
			hlog.CtxErrorf(c, "[Recovery] panic recovered: %v", r)
		}
	}()
	hlog.CtxErrorf(c, "[Recovery] err=%v\nstack=%s", err, stack)
	hlog.CtxErrorf(c, "Client: %s", ctx.Request.Header.UserAgent())
	//base := handler.BaseHandler{}
	//base.ErrorResponse(c, ctx, &consts2.SystemErr, nil)
	ctx.Abort()
}
