// Code generated by hertz generator.

package main

import (
	"empyrean_lens/dal"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	h := server.Default()

	dal.Init()

	register(h)
	h.Spin()
}
