// Code generated by hertz generator.

package notice_webhook

import (
	"codeup.aliyun.com/deeplang/lingowhale/lingowhale_backend/go_lib/middleware"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		middleware.TraceServerMiddleware(),
		middleware.RequestLogServerMiddleware(),
		middleware.RequestMetricsServerMiddleware(),
		middleware.RecoverPanicServerMw(),
	}

}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _notice_webhookMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _slsnoticewebhookMw() []app.HandlerFunc {
	// your code...
	return nil
}
