// Code generated by hertz generator.

package auth

import (
	"empyrean_lens/service"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc { return nil }
func _apiMw() []app.HandlerFunc  { return nil }

// /api/auth/* 路由需要 JWT 验证
func _authMw() []app.HandlerFunc {
	return []app.HandlerFunc{service.AuthMiddleware().MiddlewareFunc()}
}

func _logoutMw() []app.HandlerFunc { return nil }
func _meMw() []app.HandlerFunc     { return nil }

// /auth/login 和 /auth/callback 是公开路由，无需 JWT
func _auth0Mw() []app.HandlerFunc    { return nil }
func _callbackMw() []app.HandlerFunc { return nil }
func _loginMw() []app.HandlerFunc    { return nil }

// /.well-known/openid-configuration 公开
func __well_knownMw() []app.HandlerFunc       { return nil }
func _oidcconfigurationMw() []app.HandlerFunc { return nil }
func _configurationMw() []app.HandlerFunc     { return nil }

// /userinfo 需要 JWT 验证（标准 OIDC UserInfo 端点）
func _userinfoMw() []app.HandlerFunc {
	return []app.HandlerFunc{service.AuthMiddleware().MiddlewareFunc()}
}

// /introspect 和 /token 公开（token/credentials 在请求体里，服务端自行验证）
func _introspectMw() []app.HandlerFunc { return nil }
func _tokenMw() []app.HandlerFunc      { return nil }
