// Code generated by hertz generator.

package empyrean_lens

import (
	"context"
	empyrean_lens2 "empyrean_lens/service/mongo/empyrean_lens"

	empyrean_lens "empyrean_lens/biz/model/empyrean_lens"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// ErrorList .
// @router /api/v1/front_err/list [GET]
func ErrorList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req empyrean_lens.UserErrorListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(empyrean_lens.UserErrorListResp)
	service := empyrean_lens2.UserErrorService
	list, err := service.GeneralErrorList(ctx, req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp.Data = list
	c.JSON(consts.StatusOK, resp)
}

// ErrorUpload .
// @router /api/v1/front_err/upload/list [GET]
func ErrorUpload(ctx context.Context, c *app.RequestContext) {
	var err error
	var req empyrean_lens.UserErrorUploadReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(empyrean_lens.UserErrorUploadResp)
	service := empyrean_lens2.UserErrorService
	list, err := service.UploadErrorList(ctx, req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp.Data = list
	c.JSON(consts.StatusOK, resp)
}

// ErrorGenerate .
// @router /api/v1/front_err/generate/list [GET]
func ErrorGenerate(ctx context.Context, c *app.RequestContext) {
	var err error
	var req empyrean_lens.UserErrorGenerateReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(empyrean_lens.UserErrorGenerateResp)
	service := empyrean_lens2.UserErrorService
	list, err := service.GenerateErrorList(ctx, req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp.Data = list
	c.JSON(consts.StatusOK, resp)
}
