// Code generated by hertz generator.

package empyrean_lens

import (
	"context"
	"empyrean_lens/biz/handler"

	"empyrean_lens/biz/model/empyrean_lens"
	consts2 "empyrean_lens/consts"
	"empyrean_lens/service/link_trace"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// UserActions .
// @router /api/v1/link_trace/user_actions [GET]
func UserActions(ctx context.Context, c *app.RequestContext) {
	var err error
	var req empyrean_lens.UserActionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusOK, &empyrean_lens.UserActionResp{
			Code: int64(consts2.ParamBindJsonError.Code),
			Msg:  consts2.ParamBindJsonError.Msg,
		})
		return
	}
	// 未传status 返回空
	if len(req.Status) == 0 {
		c.JSON(consts.StatusOK, &empyrean_lens.UserActionResp{
			Code: 0,
			Msg:  "success",
			Data: &empyrean_lens.UserActionRespData{
				Rows:    []*empyrean_lens.UserActionRespRow{},
				HasNext: false,
			},
		})
		return
	}
	data, bizCode := link_trace.GetUserAction(ctx, req)
	if bizCode != nil {
		hlog.CtxErrorf(ctx, "[GetUserAction] error: %+v", bizCode)
		c.JSON(consts.StatusOK, &empyrean_lens.UserActionResp{
			Code: int64(bizCode.Code),
			Msg:  bizCode.Msg,
		})
		return
	}
	c.JSON(consts.StatusOK, &empyrean_lens.UserActionResp{
		Code: 0,
		Msg:  "success",
		Data: data,
	})
}

// DocLinkTrace .
// @router /api/v1/link_trace/single_doc [GET]
func DocLinkTrace(ctx context.Context, c *app.RequestContext) {
	var err error
	var req empyrean_lens.DocLinkTraceReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusOK, &empyrean_lens.DocLinkTraceResp{
			Code: int64(consts2.ParamBindJsonError.Code),
			Msg:  consts2.ParamBindJsonError.Msg,
		})
		return
	}
	data, bizCode := link_trace.LinkTrace(ctx, req.EntryType, req.EntryID)
	if bizCode != nil {
		hlog.CtxErrorf(ctx, "[LinkTrace] error: %+v", bizCode)
		c.JSON(consts.StatusOK, &empyrean_lens.DocLinkTraceResp{
			Code: int64(bizCode.Code),
			Msg:  bizCode.Msg,
		})
		return
	}
	c.JSON(consts.StatusOK, &empyrean_lens.DocLinkTraceResp{
		Code: 0,
		Msg:  "success",
		Data: data.(*empyrean_lens.DocLinkTraceRespData),
	})
}

// MultiDocLinkTrace .
// @router /api/v1/link_trace/multi_doc [GET]
func MultiDocLinkTrace(ctx context.Context, c *app.RequestContext) {
	var err error
	var req empyrean_lens.MultiDocLinkTraceReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusOK, &empyrean_lens.MultiDocLinkTraceResp{
			Code: int64(consts2.ParamBindJsonError.Code),
			Msg:  consts2.ParamBindJsonError.Msg,
		})
		return
	}
	data, bizCode := link_trace.LinkTrace(ctx, empyrean_lens.EntryTypeEnum_MULTI, req.MultiID)
	if bizCode != nil {
		hlog.CtxErrorf(ctx, "[LinkTrace] error: %+v", bizCode)
		c.JSON(consts.StatusOK, &empyrean_lens.MultiDocLinkTraceResp{
			Code: int64(bizCode.Code),
			Msg:  bizCode.Msg,
		})
		return
	}
	c.JSON(consts.StatusOK, &empyrean_lens.MultiDocLinkTraceResp{
		Code: 0,
		Msg:  "success",
		Data: data.(*empyrean_lens.MultiDocLinkTraceRespData),
	})
}

// LinkNodeLogs .
// @router /api/v1/link_trace/node_logs [GET]
func LinkNodeLogs(ctx context.Context, c *app.RequestContext) {
	var err error
	var req empyrean_lens.LinkNodeLogReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusOK, &empyrean_lens.LinkNodeLogResp{
			Code: int64(consts2.ParamBindJsonError.Code),
			Msg:  consts2.ParamBindJsonError.Msg,
		})
		return
	}
	data, bizCode := link_trace.NodeLogs(ctx, req)
	if bizCode != nil {
		hlog.CtxErrorf(ctx, "[NodeLogs] error: %+v", bizCode)
		c.JSON(consts.StatusOK, &empyrean_lens.LinkNodeLogResp{
			Code: int64(bizCode.Code),
			Msg:  bizCode.Msg,
		})
		return
	}
	c.JSON(consts.StatusOK, &empyrean_lens.LinkNodeLogResp{
		Code: 0,
		Msg:  "success",
		Data: data,
	})
}

// WcdNodeDetail .
// @router /api/v1/link_trace/wcd_oss_detail [GET]
func WcdNodeDetail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req empyrean_lens.WcdOssDetalReq
	base := handler.BaseHandler{}
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	data, bizErr := link_trace.GetWcdOssLogDetail(ctx, req)
	if bizErr != nil {
		hlog.CtxErrorf(ctx, "[WcdNodeDetail] error: %+v", bizErr)
		base.ErrorResponse(ctx, c, bizErr, err)
		return
	}

	resp := new(empyrean_lens.WcdOssDetalResp)
	resp.Data = data
	base.SuccessResponse(c, resp)
}

// WcdOssWorthlessLogs .
// @router /api/v1/link_trace/wcd_worthless [GET]
func WcdOssWorthlessLogs(ctx context.Context, c *app.RequestContext) {
	var err error
	var req empyrean_lens.WcdWorthlessReq
	err = c.BindAndValidate(&req)
	base := handler.BaseHandler{}
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	data, err := link_trace.GetWcdWorthlessLogs(ctx, req)
	if err != nil {
		hlog.CtxErrorf(ctx, "[WcdOssWorthlessLogs] error: %+v", err)
		c.String(consts.StatusBadRequest, err.Error())
	}

	resp := new(empyrean_lens.WcdWorthlessResp)
	resp.Data = data
	base.SuccessResponse(c, resp)
}
