// Code generated by hertz generator.

package empyrean_lens

import (
	"context"
	"sort"
	"time"

	"empyrean_lens/biz/handler"
	"empyrean_lens/biz/model/empyrean_lens"
	consts2 "empyrean_lens/consts"
	"empyrean_lens/service/link_trace"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// UserActions .
// @router /api/v1/link_trace/user_actions [GET]
func UserActions(ctx context.Context, c *app.RequestContext) {
	var err error
	var req empyrean_lens.UserActionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusOK, &empyrean_lens.UserActionResp{
			Code: int64(consts2.ParamBindJsonError.Code),
			Msg:  consts2.ParamBindJsonError.Msg,
		})
		return
	}
	// 未传status 返回空
	if len(req.Status) == 0 {
		c.JSON(consts.StatusOK, &empyrean_lens.UserActionResp{
			Code: 0,
			Msg:  "success",
			Data: &empyrean_lens.UserActionRespData{
				Rows:    []*empyrean_lens.UserActionRespRow{},
				HasNext: false,
			},
		})
		return
	}
	data, bizCode := link_trace.GetUserAction(ctx, req)
	if bizCode != nil {
		hlog.CtxErrorf(ctx, "[GetUserAction] error: %+v", bizCode)
		c.JSON(consts.StatusOK, &empyrean_lens.UserActionResp{
			Code: int64(bizCode.Code),
			Msg:  bizCode.Msg,
		})
		return
	}
	c.JSON(consts.StatusOK, &empyrean_lens.UserActionResp{
		Code: 0,
		Msg:  "success",
		Data: data,
	})
}

// DocLinkTrace .
// @router /api/v1/link_trace/single_doc [GET]
func DocLinkTrace(ctx context.Context, c *app.RequestContext) {
	var err error
	var req empyrean_lens.DocLinkTraceReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusOK, &empyrean_lens.DocLinkTraceResp{
			Code: int64(consts2.ParamBindJsonError.Code),
			Msg:  consts2.ParamBindJsonError.Msg,
		})
		return
	}
	_, data, bizCode := link_trace.LinkTrace(ctx, req.EntryType, req.EntryID)
	if bizCode != nil {
		hlog.CtxErrorf(ctx, "[LinkTrace] error: %+v", bizCode)
		c.JSON(consts.StatusOK, &empyrean_lens.DocLinkTraceResp{
			Code: int64(bizCode.Code),
			Msg:  bizCode.Msg,
		})
		return
	}
	c.JSON(consts.StatusOK, &empyrean_lens.DocLinkTraceResp{
		Code: 0,
		Msg:  "success",
		Data: data.(*empyrean_lens.DocLinkTraceRespData),
	})
}

// MultiDocLinkTrace .
// @router /api/v1/link_trace/multi_doc [GET]
func MultiDocLinkTrace(ctx context.Context, c *app.RequestContext) {
	var err error
	var req empyrean_lens.MultiDocLinkTraceReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusOK, &empyrean_lens.MultiDocLinkTraceResp{
			Code: int64(consts2.ParamBindJsonError.Code),
			Msg:  consts2.ParamBindJsonError.Msg,
		})
		return
	}
	_, data, bizCode := link_trace.LinkTrace(ctx, req.EntryType, req.EntryID)
	if bizCode != nil {
		hlog.CtxErrorf(ctx, "[LinkTrace] error: %+v", bizCode)
		c.JSON(consts.StatusOK, &empyrean_lens.MultiDocLinkTraceResp{
			Code: int64(bizCode.Code),
			Msg:  bizCode.Msg,
		})
		return
	}
	c.JSON(consts.StatusOK, &empyrean_lens.MultiDocLinkTraceResp{
		Code: 0,
		Msg:  "success",
		Data: data.(*empyrean_lens.MultiDocLinkTraceRespData),
	})
}

// LinkNodeLogs .
// @router /api/v1/link_trace/node_logs [GET]
func LinkNodeLogs(ctx context.Context, c *app.RequestContext) {
	var err error
	var req empyrean_lens.LinkNodeLogReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusOK, &empyrean_lens.LinkNodeLogResp{
			Code: int64(consts2.ParamBindJsonError.Code),
			Msg:  consts2.ParamBindJsonError.Msg,
		})
		return
	}
	data, bizCode := link_trace.NodeLogs(ctx, req)
	if bizCode != nil {
		hlog.CtxErrorf(ctx, "[NodeLogs] error: %+v", bizCode)
		c.JSON(consts.StatusOK, &empyrean_lens.LinkNodeLogResp{
			Code: int64(bizCode.Code),
			Msg:  bizCode.Msg,
		})
		return
	}
	// 判断是否需要分组
	if req.NeedGroup && data.Status != empyrean_lens.ActionStatusEnum_FAIL {
		// 按照输入输出分组
		sort.Slice(data.Logs, func(i, j int) bool {
			enterTime1, _ := time.Parse(consts2.DateTimeTemplate, data.Logs[i].EnterTime)
			enterTime2, _ := time.Parse(consts2.DateTimeTemplate, data.Logs[j].EnterTime)
			return enterTime1.Before(enterTime2)
		})
		// 分组
		groups := []*empyrean_lens.ApiLogGroup{}
		for idx, log := range data.Logs {
			groups = append(groups, &empyrean_lens.ApiLogGroup{
				Idx:  int32(idx + 1),
				Logs: []*empyrean_lens.ApiLog{log},
			})
		}
		data.Groups = groups
		data.Logs = nil
	}
	c.JSON(consts.StatusOK, &empyrean_lens.LinkNodeLogResp{
		Code: 0,
		Msg:  "success",
		Data: data,
	})
}

// SaveLinkTrace .
// @router /api/v1/link_trace/save [GET]
func SaveLinkTrace(ctx context.Context, c *app.RequestContext) {
	var err error
	var req empyrean_lens.SaveLinkTraceReq
	err = c.BindJSON(&req)
	if err != nil {
		c.JSON(consts.StatusOK, &empyrean_lens.SaveLinkTraceResp{
			Code: int64(consts2.ParamBindJsonError.Code),
			Msg:  consts2.ParamBindJsonError.Msg,
		})
		return
	}
	bizCode := link_trace.Save(ctx, req.EntryType, req.EntryID)
	if bizCode != nil {
		hlog.CtxErrorf(ctx, "[Save] error: %+v", bizCode)
		c.JSON(consts.StatusOK, &empyrean_lens.SaveLinkTraceResp{
			Code: int64(bizCode.Code),
			Msg:  bizCode.Msg,
		})
		return
	}
	c.JSON(consts.StatusOK, &empyrean_lens.SaveLinkTraceResp{
		Code: 0,
		Msg:  "success",
	})
}

// BatchSaveLinkTrace .
// @router /api/v1/link_trace/batch_save [POST]
func BatchSaveLinkTrace(ctx context.Context, c *app.RequestContext) {
	var err error
	var req empyrean_lens.BatchSaveLinkTraceReq
	err = c.BindJSON(&req)
	if err != nil {
		c.JSON(consts.StatusOK, &empyrean_lens.BatchSaveLinkTraceResp{
			Code: int64(consts2.ParamBindJsonError.Code),
			Msg:  consts2.ParamBindJsonError.Msg,
		})
		return
	}
	bizCode := link_trace.BatchSave(ctx, req.EntryType, req.BeginAt, req.EndAt)
	if bizCode != nil {
		hlog.CtxErrorf(ctx, "[Save] error: %+v", bizCode)
		c.JSON(consts.StatusOK, &empyrean_lens.BatchSaveLinkTraceResp{
			Code: int64(bizCode.Code),
			Msg:  bizCode.Msg,
		})
		return
	}
	c.JSON(consts.StatusOK, &empyrean_lens.BatchSaveLinkTraceResp{
		Code: 0,
		Msg:  "success",
	})
}

// WcdNodeDetail .
// @router /api/v1/link_trace/wcd_oss_detail [GET]
func WcdNodeDetail(ctx context.Context, c *app.RequestContext) {
	var err error
	var req empyrean_lens.WcdOssDetalReq
	base := handler.BaseHandler{}
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	data, bizErr := link_trace.GetWcdOssLogDetail(ctx, req)
	if bizErr != nil {
		hlog.CtxErrorf(ctx, "[WcdNodeDetail] error: %+v", bizErr)
		base.ErrorResponse(ctx, c, bizErr, err)
		return
	}

	resp := new(empyrean_lens.WcdOssDetalResp)
	resp.Data = data
	base.SuccessResponse(c, resp)
}

// WcdOssWorthlessLogs .
// @router /api/v1/link_trace/wcd_worthless [GET]
func WcdOssWorthlessLogs(ctx context.Context, c *app.RequestContext) {
	var err error
	var req empyrean_lens.WcdWorthlessReq
	err = c.BindAndValidate(&req)
	base := handler.BaseHandler{}
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	data, err := link_trace.GetWcdWorthlessLogs(ctx, req)
	if err != nil {
		hlog.CtxErrorf(ctx, "[WcdOssWorthlessLogs] error: %+v", err)
		c.String(consts.StatusBadRequest, err.Error())
	}

	resp := new(empyrean_lens.WcdWorthlessResp)
	resp.Data = data
	base.SuccessResponse(c, resp)
}

// TraceIdToEntryId .
// @router /api/v1/link_trace/trace_id_to_entry_id [GET]
func TraceIdToEntryId(ctx context.Context, c *app.RequestContext) {
	var err error
	var req empyrean_lens.TraceIdToEntryIdReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusOK, &empyrean_lens.TraceIdToEntryIdResp{
			Code: int64(consts2.ParamBindJsonError.Code),
			Msg:  consts2.ParamBindJsonError.Msg,
		})
	}
	data, bizCode := link_trace.TraceIDToEntryID(ctx, req)
	if bizCode != nil {
		hlog.CtxErrorf(ctx, "[TraceIDToEntryID] error: %+v", bizCode)
		c.JSON(consts.StatusOK, &empyrean_lens.TraceIdToEntryIdResp{
			Code: int64(bizCode.Code),
			Msg:  bizCode.Msg,
		})
		return
	}
	c.JSON(consts.StatusOK, &empyrean_lens.TraceIdToEntryIdResp{
		Code: 0,
		Msg:  "success",
		Data: data,
	})
}
