// Code generated by hertz generator.

package empyrean_lens

import (
	"context"
	"empyrean_lens/biz/handler"
	consts2 "empyrean_lens/consts"
	dal_mongo_empyrean_lens "empyrean_lens/dal/mongo/empyrean_lens"
	aliyun2 "empyrean_lens/service/aliyun"
	empyrean_lens2 "empyrean_lens/service/mongo/empyrean_lens"
	"empyrean_lens/service/passport"
	"empyrean_lens/utils"
	"fmt"
	"html/template"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/cloudwego/hertz/pkg/common/adaptor"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/protocol"

	empyrean_lens "empyrean_lens/biz/model/empyrean_lens"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

type Overview struct {
	//DailyOverview    []utils.ReventResult
	DailyOverview    []empyrean_lens2.ScoreListItem
	RealtimeOverview aliyun2.RealtimeReport
	SceneOverviews   []map[string]string
	DailyAppCrash    []empyrean_lens2.AppCrashRespData
	DailyModelResult []empyrean_lens2.DailyModelAutomationData
	Pages            []int // 添加页码数组
	CurrentPage      int64 // 添加当前页码
}

// OverviewRender .
// @router /api/log/overview [GET]
func OverviewRender(ctx context.Context, c *app.RequestContext) {
	var err error
	var req empyrean_lens.EmptyReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	//realtimeOverview, err := aliyun.RealtimeAvailability(ctx)
	realtimeOverview, err := empyrean_lens2.SystemRealtimeReportv1_1(ctx)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}
	//timeBegin := time.Date(2024, 7, 1, 0, 0, 0, 0, time.UTC)
	//dailyOverview, err := aliyun.SystemTimespanAvailability(ctx, consts2.TIMESPAN_LONGTIME)
	dailyOverview, err := empyrean_lens2.SystemScoreResult(
		ctx,
		time.Date(2024, 7, 1, 0, 0, 0, 0, time.Local),
		time.Now().Add(8*time.Hour),
	)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	//aigcCostOverview, err := empyrean_lens2.SceneResult(ctx, timeBegin, time.Now())

	dailyAppCrashOverview, err := empyrean_lens2.GetDailyAppCrashByTime(
		ctx,
		time.Date(2025, 02, 01, 0, 0, 0, 0, time.Local),
		time.Now().Add(8*time.Hour),
	)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	//todo：这里因为性能问题，临时调整为只获取最近5天的数据，后面需要优化升级
	// 获取页码参数
	// 获取所有数据
	dailyModelResult, err := empyrean_lens2.GetDailyModelAutomationByTime(
		ctx,
		time.Time{},
		time.Now().Add(8*time.Hour),
		0,  // skip 设为 0
		-1, // limit 设为 -1 表示获取所有数据
	)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	// 计算总页数
	totalPages := (len(dailyModelResult) + 9) / 10 // 每页10条数据
	pages := make([]int, totalPages)
	for i := range pages {
		pages[i] = i + 1
	}

	rw := adaptor.GetCompatResponseWriter(&c.Response)
	overview := Overview{
		DailyOverview:    dailyOverview,
		RealtimeOverview: *realtimeOverview,
		DailyAppCrash:    dailyAppCrashOverview,
		DailyModelResult: dailyModelResult,
		//SceneOverviews:   aigcCostOverview,
		Pages:       pages,
		CurrentPage: 1, // 默认第一页
	}

	tpl, err := template.ParseFiles(filepath.Join(utils.GetProjectPath(), consts2.OVERVIEW_TEMPLATE_PATH))
	wd, _ := os.Getwd()
	if err != nil {
		c.String(consts.StatusInternalServerError, fmt.Sprintf("%v PWD: %v", err.Error(), wd))
		return
	}
	if err := tpl.Execute(rw, overview); err != nil {
		c.String(consts.StatusInternalServerError, fmt.Sprintf("%v PWD: %v", err.Error(), wd))
		return
	}
}

// SystemRealtimeScore .
// @router /api/v1/report/realtime [GET]
func SystemRealtimeScore(ctx context.Context, c *app.RequestContext) {
	var err error
	var req empyrean_lens.EmptyReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(empyrean_lens.RealtimeScoreResp)

	c.JSON(consts.StatusOK, resp)
}

// SystemDailyScore .
// @router /api/v1/report/daily/score [GET]
func SystemDailyScore(ctx context.Context, c *app.RequestContext) {
	var err error
	var req empyrean_lens.DailyScoreReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	data, err := empyrean_lens2.ScoreRelatedDetailQuery(ctx, req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(empyrean_lens.DailyScoreResp)
	resp.Msg = "success"
	resp.Code = 0
	resp.Data = data
	base := handler.BaseHandler{}

	base.SuccessResponse(c, resp)
}

// SystemDailyApiFailureInfo .
// @router /api/v1/report/fail/list [GET]
func SystemDailyApiFailureInfo(ctx context.Context, c *app.RequestContext) {
	base := handler.BaseHandler{}
	var err error
	var req empyrean_lens.DailyApiFailureInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		base.ErrorResponse(ctx, c, &consts2.SystemErr, err)
		return
	}

	resp := new(empyrean_lens.ApiFailureInfoResp)
	dateBegin, err := time.Parse("2006-01-02", req.DateBegin)
	dateEnd := dateBegin.AddDate(0, 0, 1)
	if req.DateEnd != "" {
		dateEnd, err = time.Parse("2006-01-02", req.DateEnd)
	}
	if err != nil {
		if err != nil {
			base.ErrorResponse(ctx, c, &consts2.SystemErr, err)
			return
		}
	}
	result, err := empyrean_lens2.ApiFailResult(ctx, dateBegin, dateEnd)
	data := []*empyrean_lens.ApiFailureInfoRespData{}
	for _, r := range result {
		data = append(data, &empyrean_lens.ApiFailureInfoRespData{
			Date:           r.Date,
			APIName:        r.CoreApiName,
			APIPath:        r.CoreApiPath,
			Host:           r.HostName,
			NumTotalReq:    int32(r.TotalCount),
			NumErrorReq:    int32(r.FailCount),
			ErrPercent:     r.FailRate,
			NumCode3xx:     int32(r.FailStatus3xx),
			NumCode4xx:     int32(r.FailStatus4xx),
			NumCode5xx:     int32(r.FailStatus5xx),
			NumBizErrorReq: int32(r.BizCodeFailCount),
		})
	}
	resp.Data = data
	base.SuccessResponse(c, resp)
}

// SystemDbRefresh .
// @router /api/v1/report/db/refresh [POST]
func SystemDbRefresh(ctx context.Context, c *app.RequestContext) {
	var err error
	var req empyrean_lens.DbRefreshReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(empyrean_lens.DbRefreshResp)
	base := handler.BaseHandler{}
	err = aliyun2.CreateOrUpdateDatabase(ctx, int(req.Timespan), req.Rm)
	if err != nil {
		base.ErrorResponse(ctx, c, &consts2.SystemErr, err)
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// WriteProbeLogs .
// @router /api/v1/report/db/write_probe [POST]
func WriteProbeLogs(ctx context.Context, c *app.RequestContext) {
	var err error
	var req empyrean_lens.WriteProbeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	base := handler.BaseHandler{}
	if err := empyrean_lens2.SaveBatch(ctx, req); err != nil {
		base.ErrorResponse(ctx, c, &consts2.SystemErr, nil)
		return
	}

	resp := new(empyrean_lens.WriteProbeResp)
	c.JSON(consts.StatusOK, resp)
}

// SystemDbTidy .
// @router /api/v1/report/db/tidy [POST]
func SystemDbTidy(ctx context.Context, c *app.RequestContext) {
	var err error
	var req empyrean_lens.DbTidyReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	base := handler.BaseHandler{}
	if err := empyrean_lens2.ProbeLogTidy(ctx); err != nil {
		base.ErrorResponse(ctx, c, &consts2.SystemErr, nil)
		return
	}

	resp := new(empyrean_lens.DbRefreshResp)

	c.JSON(consts.StatusOK, resp)
}

// SystemDailyApiSlowInfo .
// @router /api/v1/report/slow/list [GET]
func SystemDailyApiSlowInfo(ctx context.Context, c *app.RequestContext) {
	base := handler.BaseHandler{}
	var err error
	var req empyrean_lens.DailyApiSlowInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		base.ErrorResponse(ctx, c, &consts2.SystemErr, err)
		return
	}
	dateBegin, err := time.Parse("2006-01-02", req.DateBegin)
	dateEnd := dateBegin.AddDate(0, 0, 1)
	dateBegin1Day := dateBegin.AddDate(0, 0, -1)
	dateEnd1Day := dateBegin1Day.AddDate(0, 0, 1)
	dateBegin7Day := dateBegin.AddDate(0, 0, -7)
	dateEnd7Day := dateBegin7Day.AddDate(0, 0, 1)
	if req.DateEnd != "" {
		dateEnd, err = time.Parse("2006-01-02", req.DateEnd)
	}
	if err != nil {
		if err != nil {
			base.ErrorResponse(ctx, c, &consts2.SystemErr, err)
			return
		}
	}
	result, err := empyrean_lens2.SceneResult(ctx, dateBegin, dateEnd)
	result1Day, err := empyrean_lens2.SceneResult(ctx, dateBegin1Day, dateEnd1Day)
	result7Day, err := empyrean_lens2.SceneResult(ctx, dateBegin7Day, dateEnd7Day)

	resp := new(empyrean_lens.ApiSlowInfoResp)
	data := []*empyrean_lens.ApiSlowInfoRespData{}
	for i, r := range result {
		total, e := strconv.ParseInt(r["TotalCnt"], 10, 32)
		slow, e := strconv.ParseInt(r["SlowCnt"], 10, 32)
		errCnt, e := strconv.ParseInt(r["FailCnt"], 10, 32)
		if e != nil {
			continue
		}
		slowDetails := []string{}
		failDetails := []string{}
		utils.JSONUnMarshal([]byte(r["SlowDetails"]), &slowDetails)
		utils.JSONUnMarshal([]byte(r["FailDetails"]), &failDetails)
		costs := make([][]string, 3)
		costs[0] = strings.Split(r["Costs"], ",")
		avg := make([]float64, 3)
		costs[1], costs[2] = strings.Split(result1Day[i]["Costs"], ","), strings.Split(result7Day[i]["Costs"], ",")
		for j, cost := range costs {
			for _, v := range cost {
				if v == "" {
					continue
				}
				curCost, err := strconv.ParseFloat(v, 64)
				if err != nil {
					hlog.CtxErrorf(ctx, "parse cost error: %v", err)
					base.ErrorResponse(ctx, c, &consts2.SystemErr, err)
					return
				}
				avg[j] += curCost
			}
			avg[j] /= float64(len(cost))

		}
		div1Day, div7Day := 0, 0
		if avg[1] != 0 {
			div1Day = int(avg[1])
		}
		if avg[2] != 0 {
			div7Day = int(avg[2])
		}
		data = append(data, &empyrean_lens.ApiSlowInfoRespData{
			Date:         r["Date"],
			NumTotalReq:  int32(total),
			NumSlowReq:   int32(slow),
			APIAvgCost:   avg[0],
			Host:         "",
			APIName:      r["Scene"],
			NumErrorReq:  int32(errCnt),
			SlowDetails:  slowDetails,
			FailDetails:  failDetails,
			DayOverDay:   utils.Div(avg[0]-avg[1], float64(div1Day)),
			WeekOverWeek: utils.Div(avg[0]-avg[2], float64(div7Day)),
		})
	}
	resp.Data = data
	base.SuccessResponse(c, resp)
}

// SystemDailyApiCost .
// @router /api/v1/report/probe/list [GET]
func SystemDailyApiCost(ctx context.Context, c *app.RequestContext) {
	base := handler.BaseHandler{}
	var err error
	var req empyrean_lens.ApiProbeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(empyrean_lens.ApiProbeResp)
	data, err := empyrean_lens2.ProbeListInfo(ctx, req)
	if err != nil {
		base.ErrorResponse(ctx, c, &consts2.SystemErr, err)
		return
	}
	resp.Data = data
	base.SuccessResponse(c, resp)
}

// SystemDailyApiFailureDetail .
// @router /api/v1/report/fail/detail [GET]
func SystemDailyApiFailureDetail(ctx context.Context, c *app.RequestContext) {
	base := handler.BaseHandler{}
	var err error
	var req empyrean_lens.DailyApiFailureDetailReq
	err = c.BindAndValidate(&req)
	if err != nil {
		base.ErrorResponse(ctx, c, &consts2.SystemErr, err)
		return
	}

	resp := new(empyrean_lens.ApiFailureDetailResp)
	detail, err := aliyun2.NginxApiFailureDetail(ctx, req)
	if err != nil {
		base.ErrorResponse(ctx, c, &consts2.SystemErr, err)
		return
	}
	resp.Data = detail
	base.SuccessResponse(c, resp)
}

// SystemEndToEndTraceLogs .
// @router /api/v1/report/trace/list [GET]
func SystemEndToEndTraceLogs(ctx context.Context, c *app.RequestContext) {
	base := handler.BaseHandler{}
	var err error
	var req empyrean_lens.EndToEndTraceReq
	err = c.BindAndValidate(&req)
	if err != nil {
		base.ErrorResponse(ctx, c, &consts2.SystemErr, err)
		return
	}

	resp := new(empyrean_lens.EndToEndTraceResp)
	data, err := aliyun2.EndToEndTraceLogs(ctx, req)
	if err != nil {
		base.ErrorResponse(ctx, c, &consts2.SystemErr, err)
		return
	}
	resp.Data = data
	base.SuccessResponse(c, resp)
}

// SystemProbeLogDetail .
// @router /api/v1/report/probe/detail [GET]
func SystemProbeLogDetail(ctx context.Context, c *app.RequestContext) {
	base := handler.BaseHandler{}
	var err error
	var req empyrean_lens.ProbeLogDetailReq
	err = c.BindAndValidate(&req)
	if err != nil {
		base.ErrorResponse(ctx, c, &consts2.SystemErr, err)
		return
	}

	resp := new(empyrean_lens.ProbeLogDetailResp)
	detail, err := empyrean_lens2.ProbeDetail(ctx, req)
	if err != nil {
		base.ErrorResponse(ctx, c, &consts2.SystemErr, err)
		return
	}
	resp.Data = detail
	base.SuccessResponse(c, resp)
}

// SysteTracebackLogs .
// @router /api/v1/report/traceback/list [GET]
func SysteTracebackLogs(ctx context.Context, c *app.RequestContext) {
	base := handler.BaseHandler{}
	var err error
	var req empyrean_lens.TracebackReq
	err = c.BindAndValidate(&req)
	if err != nil {
		base.ErrorResponse(ctx, c, &consts2.SystemErr, err)
		return
	}

	resp := new(empyrean_lens.TracebackResp)
	data, err := empyrean_lens2.SystemTracebackQuery(ctx, req)
	if err != nil {
		base.ErrorResponse(ctx, c, &consts2.SystemErr, err)
		return
	}
	resp.Data = data
	base.SuccessResponse(c, resp)
}

// ToolsRender .
// @router /api/log/tools [GET]
func ToolsRender(ctx context.Context, c *app.RequestContext) {
	base := handler.BaseHandler{}
	var err error
	var req empyrean_lens.EmptyReq
	err = c.BindAndValidate(&req)
	if err != nil {
		base.ErrorResponse(ctx, c, &consts2.SystemErr, err)
		return
	}

	//resp := new(empyrean_lens.EmptyResp)

	rw := adaptor.GetCompatResponseWriter(&c.Response)
	templatePath := filepath.Join(utils.GetProjectPath(), consts2.TOOLS_TEMPLATE_PATH)
	tpl, err := template.ParseFiles(templatePath)
	wd, _ := os.Getwd()
	hlog.CtxInfof(ctx, "template path: %v. wd: %v", templatePath, wd)
	if err != nil {
		c.String(consts.StatusInternalServerError, fmt.Sprintf("%v PWD: %v", err.Error(), wd))
		return
	}
	tpl.Execute(rw, nil)
}

// GetUInfo .
// @router /api/v1/report/user/info [POST]
func GetUInfo(ctx context.Context, c *app.RequestContext) {
	base := handler.BaseHandler{}
	var err error
	var req empyrean_lens.UInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		base.ErrorResponse(ctx, c, &consts2.SystemErr, err)
		return
	}

	resp := new(empyrean_lens.UInfoResp)
	data, err := passport.GetUserInfo(ctx, req)
	if err != nil {
		base.ErrorResponse(ctx, c, &consts2.SystemErr, err)
		return
	}
	resp.Data = data
	base.SuccessResponse(c, resp)
}

// RequestTrends .
// @router /api/v1/report/trend/request [GET]
func RequestTrends(ctx context.Context, c *app.RequestContext) {
	base := handler.BaseHandler{}
	var err error
	var req empyrean_lens.RequestTrendReq
	err = c.BindAndValidate(&req)
	if err != nil {
		base.ErrorResponse(ctx, c, &consts2.ParamBindJsonError, err)
		return
	}

	resp := new(empyrean_lens.RequestTrendResp)
	data, err := aliyun2.RequestTrendV2(ctx, req)
	if err != nil {
		base.ErrorResponse(ctx, c, &consts2.SystemErr, err)
		return
	}
	resp.Data = data
	base.SuccessResponse(c, resp)
}

// UploadOnlineOperation .
// @router /api/v1/report/upload/operation [POST]
func UploadOnlineOperation(ctx context.Context, c *app.RequestContext) {
	base := handler.BaseHandler{}
	var err error
	var req empyrean_lens.UploadOnlineOperationReq
	err = c.BindAndValidate(&req)
	if err != nil {
		base.ErrorResponse(ctx, c, &consts2.ParamBindJsonError, err)
		return
	}

	data, err := empyrean_lens2.UpsertOnlineOperations(ctx, req)
	if err != nil {
		base.ErrorResponse(ctx, c, &consts2.SystemErr, err)
		return
	}

	resp := new(empyrean_lens.UploadOnlineOperationResp)
	resp.Data = data
	if len(data.FailMsgs) >= 1 {
		base.ErrorResponse(ctx, c, &consts2.SystemErr, data)
		return
	}
	base.SuccessResponse(c, resp)
}

// Auth .
// @router /api/v1/report/auth [GET]
func Auth(ctx context.Context, c *app.RequestContext) {
	base := handler.BaseHandler{}
	var err error
	var req empyrean_lens.AuthReq
	err = c.BindAndValidate(&req)
	if err != nil {
		base.ErrorResponse(ctx, c, &consts2.ParamBindJsonError, nil)
		return
	}

	resp, token, bizCode := passport.Auth(ctx, &req)
	if bizCode != nil || !resp {
		c.String(403, "Not Allowed Forbidden")
	} else {
		c.SetCookie(consts2.LARK_COOKIE, token, int(consts2.LARK_AUTH_EXPIRE_TIME), "/", consts2.DOMAIN_PATH, protocol.CookieSameSiteLaxMode, true, true)
		c.Redirect(302, []byte(consts2.HOME_PATH))
	}
}

// SystemEndToEndUserTraceLogs .
// @router /api/v1/report/user_trace/list [GET]
func SystemEndToEndUserTraceLogs(ctx context.Context, c *app.RequestContext) {
	base := handler.BaseHandler{}
	var err error
	var req empyrean_lens.EndToEndUserTraceReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(empyrean_lens.EndToEndUserTraceResp)
	logs, err := aliyun2.EndToEndUserTraceLogs(ctx, req)
	if err != nil {
		base.ErrorResponse(ctx, c, &consts2.SystemErr, err)
	}
	resp.Data = logs

	base.SuccessResponse(c, resp)
}

// GetOnlineOperation .
// @router /api/v1/report/online_operation [GET]
func GetOnlineOperation(ctx context.Context, c *app.RequestContext) {
	base := handler.BaseHandler{}
	var err error
	var req empyrean_lens.OnlineOperationReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(empyrean_lens.OnlineOperationResp)
	data, err := empyrean_lens2.FindOnlineOperations(ctx, req)
	if err != nil {
		base.ErrorResponse(ctx, c, &consts2.SystemErr, err)
		return
	}

	resp.Data = data
	base.SuccessResponse(c, resp)
}

// UserActionInfo .
// @router /user_action_info [POST]
func UserActionInfo(ctx context.Context, c *app.RequestContext) {
	base := handler.BaseHandler{}
	var err error
	var req empyrean_lens.UserActionInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(empyrean_lens.UserActionInfoResp)
	data, err := passport.GetUserActionTimeline(ctx, req)
	if err != nil {
		base.ErrorResponse(ctx, c, &consts2.SystemErr, err)
		return
	}
	resp.Data = data
	base.SuccessResponse(c, resp)
}

// AppCrashDetails .
// @router /api/v1/report/app_crash [GET]
func AppCrashDetails(ctx context.Context, c *app.RequestContext) {
	var err error
	var req empyrean_lens.AppCrashDetailReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(empyrean_lens.AppCrashDetailResp)
	//data, err :=
	data, err := empyrean_lens2.GetCrashDetailsByDate(ctx, req.Date, req.Platform)
	if err != nil {
		c.String(int(consts2.SystemErr.Code), err.Error())
		return
	}

	resp.Data = data
	c.JSON(consts.StatusOK, resp)
}

// AppCrashBatchSave .
// @router /api/v1/report/app_crash/batch_save [POST]
func AppCrashBatchSave(ctx context.Context, c *app.RequestContext) {
	var err error
	var req empyrean_lens.AppCrashBatchSaveReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp := new(empyrean_lens.AppCrashBatchSaveResp)
	beginDate, endDate := req.BeginDate, req.EndDate
	beginTime, err := time.ParseInLocation("2006-01-02", beginDate, time.Local)
	if err != nil {
		hlog.CtxErrorf(ctx, "parse begin date error: %v", err)
		resp.Code = int64(consts2.ParamBindJsonError.Code)
		resp.Msg = consts2.ParamBindJsonError.Msg
		c.JSON(consts.StatusOK, resp)
		return
	}
	endTime, err := time.ParseInLocation("2006-01-02", endDate, time.Local)
	if err != nil {
		hlog.CtxErrorf(ctx, "parse end date error: %v", err)
		resp.Code = int64(consts2.ParamBindJsonError.Code)
		resp.Msg = consts2.ParamBindJsonError.Msg
		c.JSON(consts.StatusOK, resp)
		return
	}
	// check if begintime or endtime after now
	if beginTime.After(time.Now()) || endTime.After(time.Now()) {
		hlog.CtxErrorf(ctx, "begin time or end time is after now")
		resp.Code = int64(consts2.ParamBindJsonError.Code)
		resp.Msg = consts2.ParamBindJsonError.Msg
		c.JSON(consts.StatusOK, resp)
		return
	}
	if beginTime.After(endTime) {
		hlog.CtxErrorf(ctx, "begin time is after end time")
		resp.Code = int64(consts2.ParamBindJsonError.Code)
		resp.Msg = consts2.ParamBindJsonError.Msg
		c.JSON(consts.StatusOK, resp)
	}
	for beginTime.Before(endTime) {
		date := beginTime.Format("2006-01-02")
		err := empyrean_lens2.UpdateLatestAppCrashInfo(ctx, date)
		if err != nil {
			hlog.CtxErrorf(ctx, "update app crash info error: %v", err)
			resp.Code = int64(consts2.SystemErr.Code)
			resp.Msg = consts2.SystemErr.Msg
			c.JSON(consts.StatusOK, resp)
			return
		}
		beginTime = beginTime.AddDate(0, 0, 1)
	}
	resp.Msg = "success"
	c.JSON(consts.StatusOK, resp)
}

// ModelAutomation .
// @router /api/v1/report/model_automation [GET]
func ModelAutomation(ctx context.Context, c *app.RequestContext) {
	var err error
	var req empyrean_lens.ModelAutomationReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(empyrean_lens.ModelAutomationResp)
	beginTimeStr, endTimeStr := req.Date+" 00:00:00", req.Date+" 23:59:59"
	beginTime, err := time.ParseInLocation("2006-01-02 15:04:05", beginTimeStr, time.Local)
	if err != nil {
		hlog.CtxErrorf(ctx, "parse begin time error: %v", err)
		resp.Code = int64(consts2.ParamBindJsonError.Code)
		resp.Msg = consts2.ParamBindJsonError.Msg
		c.JSON(consts.StatusOK, resp)
		return
	}
	endTime, err := time.ParseInLocation("2006-01-02 15:04:05", endTimeStr, time.Local)
	if err != nil {
		hlog.CtxErrorf(ctx, "parse end time error: %v", err)
		resp.Code = int64(consts2.ParamBindJsonError.Code)
		resp.Msg = consts2.ParamBindJsonError.Msg
		c.JSON(consts.StatusOK, resp)
		return
	}

	data, err := empyrean_lens2.GetModelAutomationInfoByTime(ctx, beginTime, endTime, req.EntryType, req.FailOrTotal)
	if err != nil {
		hlog.CtxErrorf(ctx, "get model automation info error: %v", err)
		resp.Code = int64(consts2.SystemErr.Code)
		resp.Msg = consts2.SystemErr.Msg
		c.JSON(consts.StatusOK, resp)
		return
	}

	resp.Data = data
	c.JSON(consts.StatusOK, resp)
}

// ModelCaseResult .
// @router /api/v1/report/model_case_result [GET]
func ModelCaseResult(ctx context.Context, c *app.RequestContext) {
	var err error
	var req empyrean_lens.ModelCaseResultReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(empyrean_lens.ModelCaseResultResp)

	beginTimestr, endTimestr := req.Date+" 00:00:00", req.Date+" 23:59:59"
	beginTime, err := time.ParseInLocation("2006-01-02 15:04:05", beginTimestr, time.Local)
	if err != nil {
		hlog.CtxErrorf(ctx, "parse begin time error: %v", err)
		resp.Code = int64(consts2.ParamBindJsonError.Code)
		resp.Msg = consts2.ParamBindJsonError.Msg
		c.JSON(consts.StatusOK, resp)
		return
	}
	endTime, err := time.ParseInLocation("2006-01-02 15:04:05", endTimestr, time.Local)
	if err != nil {
		hlog.CtxErrorf(ctx, "parse end time error: %v", err)
		resp.Code = int64(consts2.ParamBindJsonError.Code)
		resp.Msg = consts2.ParamBindJsonError.Msg
		c.JSON(consts.StatusOK, resp)
		return
	}
	data, err := empyrean_lens2.GetCaseResultsByTime(ctx, beginTime, endTime, req.EntryType, req.CaseType, req.FailOrTotal)
	if err != nil {
		hlog.CtxErrorf(ctx, "get model case result error: %v", err)
		resp.Code = int64(consts2.SystemErr.Code)
		resp.Msg = consts2.SystemErr.Msg
		c.JSON(consts.StatusOK, resp)
		return
	}
	resp.Data = data

	c.JSON(consts.StatusOK, resp)
}

// ModelCaseInfoSave .
// @router /api/v1/report/model/save [POST]
func ModelCaseInfoSave(ctx context.Context, c *app.RequestContext) {
	var err error
	var req empyrean_lens.ModelCaseInfoSaveReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(empyrean_lens.ModelCaseInfoSaveResp)
	if req.DbName == "model_automation" {
		returnId, err := empyrean_lens2.SaveModelAutomationInfo(ctx, req.Info)
		if err != nil {
			hlog.CtxErrorf(ctx, "save model automation info error: %v", err)
			resp.Code = int64(consts2.SystemErr.Code)
			resp.Msg = consts2.SystemErr.Msg
			//c.JSON(consts.StatusOK, resp)
		} else {
			resp.Code = 0
			resp.Msg = returnId.Hex()
		}
		//c.JSON(consts.StatusOK, resp)
	} else if req.DbName == "model_case_result" {
		returnId, err := empyrean_lens2.SaveModelCaseResultInfo(ctx, req.Info)
		if err != nil {
			hlog.CtxErrorf(ctx, "save model case result info error: %v", err)
			resp.Code = int64(consts2.SystemErr.Code)
			resp.Msg = consts2.SystemErr.Msg
			//c.JSON(consts.StatusOK, resp)
		} else {
			resp.Code = 0
			resp.Msg = returnId.Hex()
		}
		//c.JSON(consts.StatusOK, resp)
	}

	c.JSON(consts.StatusOK, resp)
}

// GetDailyModelAutomationStats .
// @router /api/v1/report/daily_model_automation_stats [GET]
func GetDailyModelAutomationStats(ctx context.Context, c *app.RequestContext) {
	var err error
	var req empyrean_lens.DailyModelAutomationStatsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(empyrean_lens.DailyModelAutomationStatsResp)

	// 解析开始和结束时间
	beginTime, err := time.Parse("2006-01-02", req.StartTime)
	if err != nil {
		resp.Code = int64(consts2.RetParamError.Code)
		resp.Msg = "无效的开始时间格式"
		c.JSON(consts.StatusOK, resp)
		return
	}
	endTime, err := time.Parse("2006-01-02", req.EndTime)
	if err != nil {
		resp.Code = int64(consts2.RetParamError.Code)
		resp.Msg = "无效的结束时间格式"
		c.JSON(consts.StatusOK, resp)
		return
	}

	// 从新的数据库表中获取统计数据
	stats, err := dal_mongo_empyrean_lens.NewDailyAutomationStatsDao().GetStatsByDateRange(ctx, beginTime, endTime)
	if err != nil {
		hlog.CtxErrorf(ctx, "get daily automation stats error: %v", err)
		resp.Code = int64(consts2.SystemErr.Code)
		resp.Msg = consts2.SystemErr.Msg
		c.JSON(consts.StatusOK, resp)
		return
	}

	// 构建响应数据
	resp.Data = make([]*empyrean_lens.DailyModelAutomationStatsRespData, len(stats))
	for i, stat := range stats {
		resp.Data[i] = &empyrean_lens.DailyModelAutomationStatsRespData{
			Date:           stat.Date,
			SingleFailNum:  int32(stat.SingleFailNum),
			SingleTotalNum: int32(stat.SingleTotalNum),
			SingleDocNum:   int32(stat.SingleDocNum),
			WebFailNum:     int32(stat.WebFailNum),
			WebTotalNum:    int32(stat.WebTotalNum),
			WebDocNum:      int32(stat.WebDocNum),
			MultiFailNum:   int32(stat.MultiFailNum),
			MultiTotalNum:  int32(stat.MultiTotalNum),
			MultiDocNum:    int32(stat.MultiDocNum),
		}
	}

	resp.Code = 0
	resp.Msg = "success"
	c.JSON(consts.StatusOK, resp)
}
