# 服务器配置
server:
  port: ":19001"
  name: "empyreanLens"

mongo_lingo:
  # 安全起见，用只读账号
  addr: "mongodb://svr_wenhao:unCNS0SLpHY%23S9Or2@dds-8vb43194a1bfeef41943-pub.mongodb.zhangbei.rds.aliyuncs.com:3717,dds-8vb43194a1bfeef42299-pub.mongodb.zhangbei.rds.aliyuncs.com:3717/lingo?replicaSet=mgset-518525368"
  databaseName: lingo
  maxPoolSize: 1000

mongo_empyreanlens:
  addr: "mongodb://svr_empyrean_lens:D2xcKpc_Umk838U@dds-8vb43194a1bfeef42.mongodb.zhangbei.rds.aliyuncs.com:3717,dds-8vb43194a1bfeef41.mongodb.zhangbei.rds.aliyuncs.com:3717/empyrean_lens?replicaSet=mgset-518525368"
  databaseName: empyrean_lens
  maxPoolSize: 1000
  shadow: ""

# 日志配置
logger:
  log_path: './logs/system'
  log_level: "info"

redis:
  addrs: ["deeplang-redis-private.redis.zhangbei.rds.aliyuncs.com:6379"]
  username: "svr_query"
  password: "REDACTED"

# 飞书配置
lark:
  appId: "cli_a668c41a0f64d013"
  appSecret: "REDACTED"
  jwtSecret: "REDACTED"
  authNames:
    - "郭晨旭"
    - "闻豪"
    - "刘勇"
    - "程振方"
    - "冯晋"
    - "李鑫亮"
    - "李国鑫"
    - "崔恩博"
    - "闫旭斌"
    - "张盈麟"
    - "张廷明"
    - "侯佳林"