# 服务器配置
server:
  port: ":19001"
  name: "empyreanLens"

mongo_lingo:
  addr: "mongodb://svr_yanxubin:9fck23!g$i7k1%40eA@10.0.6.1:27017/empyrean_lens?authSource=admin&directConnection=true"
  databaseName: lingo
  maxPoolSize: 1000

mongo_plugin:
  # addr: "mongodb://svr_yanxubin:9fck23!g$i7k1%40eA@10.0.6.1:27017/plugin_collection?authSource=admin&directConnection=true"
  # databaseName: plugin_collection
  # maxPoolSize: 1000
  addr: "mongodb://svr_liuyong:KSsCNS0SLpHY#S9Oro@dds-8vb43194a1bfeef41943-pub.mongodb.zhangbei.rds.aliyuncs.com:3717,dds-8vb43194a1bfeef42299-pub.mongodb.zhangbei.rds.aliyuncs.com:3717/lingowhale_plugin?replicaSet=mgset-518525368"
  databaseName: lingowhale_plugin
  maxPoolSize: 1000

mongo_bi:
  # addr: "mongodb://svr_yanxubin:9fck23!g$i7k1%40eA@10.0.6.1:27017/plugin_collection?authSource=admin&directConnection=true"
  # databaseName: plugin_collection
  # maxPoolSize: 1000
  addr: "mongodb://svr_liuyong:KSsCNS0SLpHY#S9Oro@dds-8vb43194a1bfeef41943-pub.mongodb.zhangbei.rds.aliyuncs.com:3717,dds-8vb43194a1bfeef42299-pub.mongodb.zhangbei.rds.aliyuncs.com:3717/lingowhale_bi?replicaSet=mgset-518525368"
  databaseName: lingowhale_bi
  maxPoolSize: 1000

mongo_empyreanlens:
  addr: "mongodb://svr_yanxubin:9fck23!g$i7k1%40eA@10.0.6.1:27017/empyrean_lens?authSource=admin&directConnection=true"
  databaseName: empyrean_lens
  maxPoolSize: 1000

# 日志配置
logger:
  log_path: './logs/system'
  log_level: "error"

# redis:
#   addrs: ["localhost:7000"]
#   password: 'root'
#   maxretries: 1

redis:
  addrs: ["47.92.241.26:6379"]
  password: 'MK6MuYGay'
  maxretries: 1


# 飞书配置
lark:
  appId: "cli_a668c41a0f64d013"
  appSecret: "REDACTED"
  jwtSecret: "REDACTED"
  auth:
    names:
    emails:
    mobiles:
    employee_nos:
      - D077
      - P104
      - D013
      - D067
      - D041