# 日志配置
logger:
  log_path: "./logs/system"
  log_level: "debug"

api:
  save_link_trace: "https://empyrean-lens.lingowhale.com/api/v1/link_trace/save"
  batch_save_link_trace: "https://empyrean-lens.lingowhale.com/api/v1/link_trace/batch_save"
  batch_update_link_trace: "https://empyrean-lens.lingowhale.com/api/v1/link_trace/batch_update_fail_record"

mns:
  save_link_trace:
    name: "save-link-trace-prod"
  batch_save_link_trace:
    name: "batch_save_link_trace"
  batch_update_link_trace:
    name: "batch_update_link_trace"
