// Code generated by hertz generator.

package notice_webhook

import (
	"context"
	"empyrean_lens/biz/model/empyrean_lens/notice_webhook"
	"empyrean_lens/service"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// SlsNoticeWebhook .
// @router /api/v1/notice_webhook/sls_notice [POST]
func SlsNoticeWebhook(ctx context.Context, c *app.RequestContext) {
	var err error
	var req notice_webhook.SlsNoticeWebhookReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	hlog.CtxInfof(ctx, "headers: %v", c.Request.Header.String())
	hlog.CtxInfof(ctx, "body: %v", string(c.Request.Body()))

	s := service.NewSlsNoticeWebhookService()
	resp, bizErr := s.SlsNoticeWebhook(ctx, &req)
	if bizErr != nil {
		c.JSON(consts.StatusOK, bizErr)
		return
	}

	c.JSON(consts.StatusOK, resp)
}
