// Code generated by hertz generator.

package notice_webhook

import (
	"context"
	notice_webhook "empyrean_lens/biz/model/empyrean_lens/notice_webhook"
	"empyrean_lens/service"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// SlsNoticeWebhook .
// @router /api/v1/notice_webhook/sls_notice [POST]
func SlsNoticeWebhook(ctx context.Context, c *app.RequestContext) {
	req := notice_webhook.SlsNoticeWebhookReq{
		RawBody: string(c.Request.Body()),
	}
	hlog.CtxInfof(ctx, "headers: %v", c.Request.Header.String())
	hlog.CtxInfof(ctx, "body len: %d", len(req.RawBody))

	s := service.NewSlsNoticeWebhookService()
	resp, bizErr := s.SlsNoticeWebhook(ctx, &req)
	if bizErr != nil {
		c.JSON(consts.StatusOK, bizErr)
		return
	}

	c.JSON(consts.StatusOK, resp)
}
