// Code generated by hertz generator.

package empyrean_lens

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _logMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _logrenderMw() []app.HandlerFunc {
	// your code...
	return nil
}
