// Code generated by hertz generator.

package empyrean_lens

import (
	"context"
	"empyrean_lens/conf"
	"empyrean_lens/consts"
	"empyrean_lens/utils"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/hlog"
)

func CookieMiddleWare() app.HandlerFunc {
	return func(c context.Context, ctx *app.RequestContext) {
		path := string(ctx.Path())
		if path == "/api/v1/report/auth" {
			ctx.Next(c)
			return
		}

		cookie := string(ctx.Request.Header.Cookie(consts.LARK_COOKIE))
		claim, err := utils.ParseJWT(cookie, conf.GetLark().JwtSecret)
		if err != nil {
			hlog.CtxErrorf(c, "jwt parse error: %+v", err)
			ctx.String(403, "No Auth Forbidden")
			ctx.Abort()
			return
		}
		if username, ok := claim[consts.LARK_USERNAME].(string); ok && utils.InSlice(username, conf.GetLark().AuthNames) {
			ctx.Next(c)
			return
		}
		ctx.String(403, "Auth Fail Forbidden")
		ctx.Abort()
	}
}

func rootMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		CookieMiddleWare(),
	}
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _logMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _logrenderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _overviewrenderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _reportMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemrealtimescoreMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dailyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemdailyscoreMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemdailyapifailureinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemdailyapicostMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dbMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemdbrefreshMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _writeprobelogsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemdbtidyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _realdatarenderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemrealdataMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _failMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _probeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _slowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemdailyapislowinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemdailyapifailuredetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemendtoendtracelogsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _traceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemprobelogdetailMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systetracebacklogsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _tracebackMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _toolsrenderMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _trendMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _requesttrendsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadonlineoperationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _authMw() []app.HandlerFunc {
	// your code...
	return nil
}
