// Code generated by hertz generator. DO NOT EDIT.

package empyrean_lens

import (
	empyrean_lens "empyrean_lens/biz/handler/empyrean_lens"
	"github.com/cloudwego/hertz/pkg/app/server"
)

/*
 This file will register all the routes of the services in the master idl.
 And it will update automatically when you use the "update" command for the idl.
 So don't modify the contents of the file, or your code will be deleted when it is updated.
*/

// Register register routes based on the IDL 'api.${HTTP Method}' annotation.
func Register(r *server.Hertz) {

	root := r.Group("/", rootMw()...)
	{
		_api := root.Group("/api", _apiMw()...)
		{
			_log := _api.Group("/log", _logMw()...)
			_log.GET("/overview", append(_overviewrenderMw(), empyrean_lens.OverviewRender)...)
			_log.GET("/tools", append(_toolsrenderMw(), empyrean_lens.ToolsRender)...)
		}
		{
			_v1 := _api.Group("/v1", _v1Mw()...)
			{
				_front_err := _v1.Group("/front_err", _front_errMw()...)
				_front_err.GET("/list", append(_errorlistMw(), empyrean_lens.ErrorList)...)
				{
					_generate := _front_err.Group("/generate", _generateMw()...)
					_generate.GET("/list", append(_errorgenerateMw(), empyrean_lens.ErrorGenerate)...)
				}
				{
					_upload := _front_err.Group("/upload", _uploadMw()...)
					_upload.GET("/list", append(_erroruploadMw(), empyrean_lens.ErrorUpload)...)
				}
			}
			{
				_link_trace := _v1.Group("/link_trace", _link_traceMw()...)
				_link_trace.POST("/batch_save", append(_batchsavelinktraceMw(), empyrean_lens.BatchSaveLinkTrace)...)
				_link_trace.GET("/download_user_actions", append(_downloaduseractionsMw(), empyrean_lens.DownloadUserActions)...)
				_link_trace.GET("/multi_doc", append(_multidoclinktraceMw(), empyrean_lens.MultiDocLinkTrace)...)
				_link_trace.GET("/node_logs", append(_linknodelogsMw(), empyrean_lens.LinkNodeLogs)...)
				_link_trace.POST("/save", append(_savelinktraceMw(), empyrean_lens.SaveLinkTrace)...)
				_link_trace.GET("/single_doc", append(_doclinktraceMw(), empyrean_lens.DocLinkTrace)...)
				_link_trace.GET("/trace_id_to_entry_id", append(_traceidtoentryidMw(), empyrean_lens.TraceIdToEntryId)...)
				_link_trace.POST("/update", append(_updateentryinfoMw(), empyrean_lens.UpdateEntryInfo)...)
				_link_trace.GET("/user_actions", append(_useractionsMw(), empyrean_lens.UserActions)...)
				_link_trace.GET("/wcd_oss_detail", append(_wcdnodedetailMw(), empyrean_lens.WcdNodeDetail)...)
				_link_trace.GET("/wcd_worthless", append(_wcdossworthlesslogsMw(), empyrean_lens.WcdOssWorthlessLogs)...)
			}
			{
				_report := _v1.Group("/report", _reportMw()...)
				_report.GET("/auth", append(_authMw(), empyrean_lens.Auth)...)
				_report.GET("/online_operation", append(_getonlineoperationMw(), empyrean_lens.GetOnlineOperation)...)
				_report.GET("/realtime", append(_systemrealtimescoreMw(), empyrean_lens.SystemRealtimeScore)...)
				{
					_daily := _report.Group("/daily", _dailyMw()...)
					_daily.GET("/score", append(_systemdailyscoreMw(), empyrean_lens.SystemDailyScore)...)
				}
				{
					_db := _report.Group("/db", _dbMw()...)
					_db.POST("/refresh", append(_systemdbrefreshMw(), empyrean_lens.SystemDbRefresh)...)
					_db.POST("/tidy", append(_systemdbtidyMw(), empyrean_lens.SystemDbTidy)...)
					_db.POST("/write_probe", append(_writeprobelogsMw(), empyrean_lens.WriteProbeLogs)...)
				}
				{
					_fail := _report.Group("/fail", _failMw()...)
					_fail.GET("/detail", append(_systemdailyapifailuredetailMw(), empyrean_lens.SystemDailyApiFailureDetail)...)
					_fail.GET("/list", append(_systemdailyapifailureinfoMw(), empyrean_lens.SystemDailyApiFailureInfo)...)
				}
				{
					_probe := _report.Group("/probe", _probeMw()...)
					_probe.GET("/detail", append(_systemprobelogdetailMw(), empyrean_lens.SystemProbeLogDetail)...)
					_probe.GET("/list", append(_systemdailyapicostMw(), empyrean_lens.SystemDailyApiCost)...)
				}
				{
					_slow := _report.Group("/slow", _slowMw()...)
					_slow.GET("/list", append(_systemdailyapislowinfoMw(), empyrean_lens.SystemDailyApiSlowInfo)...)
				}
				{
					_trace := _report.Group("/trace", _traceMw()...)
					_trace.GET("/list", append(_systemendtoendtracelogsMw(), empyrean_lens.SystemEndToEndTraceLogs)...)
				}
				{
					_traceback := _report.Group("/traceback", _tracebackMw()...)
					_traceback.GET("/list", append(_systetracebacklogsMw(), empyrean_lens.SysteTracebackLogs)...)
				}
				{
					_trend := _report.Group("/trend", _trendMw()...)
					_trend.GET("/request", append(_requesttrendsMw(), empyrean_lens.RequestTrends)...)
				}
				{
					_upload0 := _report.Group("/upload", _upload0Mw()...)
					_upload0.POST("/online_operation", append(_uploadonlineoperationMw(), empyrean_lens.UploadOnlineOperation)...)
				}
				{
					_user := _report.Group("/user", _userMw()...)
					_user.GET("/info", append(_getuinfoMw(), empyrean_lens.GetUInfo)...)
					_user.POST("/user_action_info", append(_useractioninfoMw(), empyrean_lens.UserActionInfo)...)
				}
				{
					_user_trace := _report.Group("/user_trace", _user_traceMw()...)
					_user_trace.GET("/list", append(_systemendtoendusertracelogsMw(), empyrean_lens.SystemEndToEndUserTraceLogs)...)
				}
			}
		}
	}
}
