// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	empyrean_lens "empyrean_lens/biz/router/empyrean_lens"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	empyrean_lens.Register(r)
}
