// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	empyrean_lens_auth "empyrean_lens/biz/router/empyrean_lens/auth"
	empyrean_lens_notice_webhook "empyrean_lens/biz/router/empyrean_lens/notice_webhook"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	empyrean_lens_auth.Register(r)

	empyrean_lens_notice_webhook.Register(r)
}
